spring.application.name=wexassessment

# Default Database: In-Memory H2 (Works for Local Dev and Testing)
spring.datasource.url=jdbc:h2:mem:transactionsdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.h2.console.enabled=true
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

# JPA & Validation Config
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Web Validation & Jackson
server.error.include-binding-errors=always
server.error.include-message=always
spring.jackson.property-naming-strategy=SNAKE_CASE

# External Integrations
app.treasury-api.base-url=https://api.fiscaldata.treasury.gov/services/api/fiscal_service/
app.treasury-api.endpoints.exchage-rates=v1/accounting/od/rates_of_exchange
