# Connection Overrides for Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/transaction_db
spring.datasource.username=user
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver

# Production performance safeguard overrides
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false